import type { TimelineEvent } from "../../../types";

export const unit01Timeline: TimelineEvent[] = [
  { year: "1862", label: "משה הס: 'רומי וירושלים'", description: "חזון מוקדם של תחייה לאומית יהודית — ראשון ה'אבות המייסדים' שלפני הרצל.", category: "organic" },
  { year: "1881", label: "פינסקר: 'אוטואמנציפציה'", description: "חיבור הרצליאני-במהותו שיצא ברוסיה — דוגמה לחריג שמערער על ההקבלה גיאוגרפיה=תפיסה.", category: "functional", sectionRef: "u01-s04" },
  { year: "1882", label: "הקמת חיבת ציון", description: "התיישבות פילנתרופית בארץ ישראל בלי דרישה למעמד מדיני.", category: "general" },
  { year: "1889", label: "אחד העם: 'לא זה הדרך'; בני משה", description: "חיבור הביכורים של אחד העם + הקמת מסדר חשאי אליטיסטי.", category: "organic", sectionRef: "u01-s16" },
  { year: "1890", label: "בירנבאום טבע 'ציונות'", description: "מבדיל בין 'ציונות' (פוליטי) ל'חיבת ציון' (פילנתרופי).", category: "functional", sectionRef: "u01-s05" },
  { year: "1891", label: "אחד העם: 'עבדות בתוך חירות'", description: "ניתוח של היהודי המתבולל כעבד תרבותי של החברה המארחת.", category: "organic", sectionRef: "u01-s14" },
  { year: "1896", label: "הרצל: 'מדינת היהודים'", description: "החיבור המכונן של הציונות המדינית.", category: "functional", sectionRef: "u01-s07" },
  { year: "1897", label: "קונגרס ציוני ראשון בבזל", description: "תכנית בזל — דרישה ל'בית מולדת מובטח על פי המשפט הפומבי'.", category: "functional", sectionRef: "u01-s10" },
  { year: "1898", label: "נורדאו: 'יהדות השרירים'", description: "נאום בקונגרס השני — תחייה גופנית-לאומית.", category: "functional", sectionRef: "u01-s12" },
  { year: "1901", label: "הקמת קק\"ל; הפראקציה הדמוקרטית", description: "מוסד פיננסי לרכישת אדמות + סיעה אידיאולוגית ראשונה.", category: "general", sectionRef: "u01-s21" },
  { year: "1902", label: "הרצל: 'אלטנוילנד'; ביקורת אחד העם; הקמת המזרחי", description: "הרומן האוטופי של הרצל + תגובת אחד העם החריפה + סיעה דתית-לאומית.", category: "synthesis", sectionRef: "u01-s09" },
  { year: "1903", label: "משבר אוגנדה", description: "הצעה בריטית לטריטוריה במזרח אפריקה — מבחן הציר פונקציונלי/אורגני.", category: "crisis", sectionRef: "u01-s11" },
  { year: "1904", label: "מות הרצל", description: "וולפסון יורש את הנשיאות. תחילת המאבק בין פוליטיים למעשיים.", category: "crisis", sectionRef: "u01-s17" },
  { year: "1905", label: "קונגרס השביעי דוחה אוגנדה; ITO פרשו", description: "זנגוויל וקבוצתו פורשים — פונקציונליסטים טהורים.", category: "crisis", sectionRef: "u01-s11" },
  { year: "1906", label: "ועידת הלסינגפורס; המשרד הארץ-ישראלי", description: "ועידה ציוני רוסיה: סינתזה + Gegenwartsarbeit. הקמת משרד התיישבותי.", category: "synthesis", sectionRef: "u01-s19" },
  { year: "1907", label: "קונגרס שמיני — המעשיים עולים", description: "אוסישקין מוביל את התפנית אל ההתיישבות הפעילה.", category: "general", sectionRef: "u01-s18" },
  { year: "1908", label: "רופין מגיע ליפו; מהפכת הטורקים הצעירים", description: "מודרניזציה של ההתיישבות + כשלון הדיפלומטיה מול הטורקים.", category: "crisis", sectionRef: "u01-s18" },
  { year: "1911", label: "ורבורג נשיא ההסתדרות", description: "ניצחון המעשיים בקונגרס ה-11. אחד העם משתתף כמשקיף.", category: "synthesis", sectionRef: "u01-s18" },
  { year: "1917", label: "הצהרת בלפור", description: "ההצלחה הדיפלומטית הראשונה אחרי 20 שנה — תפקיד מכריע של ויצמן.", category: "functional", sectionRef: "u01-s20" },
  { year: "1920", label: "ויצמן נשיא ההסתדרות הציונית", description: "גילם את מדיניות הסינתזה = הציונות הכללית בגוף.", category: "synthesis", sectionRef: "u01-s20" },
  { year: "1921", label: "קונגרס 12 — 73% ציונים כלליים", description: "שיא הציונות הכללית. ההסתדרות תחת מנדט בריטי.", category: "general", sectionRef: "u01-s21" },
  { year: "1925", label: "הרוויזיוניזם של ז'בוטינסקי נוסד", description: "אופוזיציה לוויצמן — תקיפת מדיניותו ועליית תנועת העבודה.", category: "crisis", sectionRef: "u01-s24" },
  { year: "1931", label: "קונגרס 17 — רק 53% ציונים כלליים", description: "ירידה מהירה. הציונות הכללית מאבדת את המרכזיות הקואליציונית.", category: "general", sectionRef: "u01-s21" },
  { year: "1935", label: "פיצול א/ב בציונים הכלליים", description: "ועידת קרקוב — קבוצה א פייסנית עם ויצמן ועם תנועת העבודה; קבוצה ב באופוזיציה.", category: "crisis", sectionRef: "u01-s21" },
  { year: "1936", label: "ולטש: 'הציונות הכללית'", description: "ההסבר הפילוסופי המעמיק ביותר — 'דרך הביניים היצירתית'.", category: "general", sectionRef: "u01-s23" },
];
